#' Obtaining Latent Normal Variables
#'
#' Binary data are often augmented with latent Normally distributed variables in Bayesian Statistics.
#' It is easier to do statistics on these Normal latent variables (generated by this function) than on binary observed variables.
#' The function returns an N by I*M Matrix, where N, I and M are the number of people, items, and time points, respectively.
#' @param thet Latent ability measures
#' @param responses A matrix of responses
#' @param ak A vector of item-level discrimination values
#' @param bk A vector of item-level difficulties
#' @keywords Normal Augmentation
#' @export
#' @examples
#' getZs()
# Returns latent outcome variables
getZs <- function(thet, responses, ak, bk){
  respVec <- unlist(responses, use.names = F) ## responses[1:1000, 1] == respVec[1:1000]
  nItems <- length(ak)
  aVec <- rep(rep(ak, times = 1, each=nLGM), 4)
  bVec <- rep(rep(bk, times = 1, each=nLGM), 4)
  iVec <- c(rep(thet[ , 1], times=nItems), rep(thet[ , 2], times=nItems), rep(thet[ , 3], times=nItems), rep(thet[ ,4], times=nItems))
  zVec <- rtruncnorm(n=4*nLGM*nItems, mean=aVec*iVec - bVec, a = ifelse(respVec == 1,  0, -Inf), b = ifelse(respVec == 1,  Inf, 0))
  zMat <- matrix(zVec, nLGM, nItems*4)
  return(zMat)
}
